### ISSUE TITLE
Pull Requeet by Pushan Verma

### ISSUE THREAD

**Issue by pushanverma** [RAJAT1402/IOSD_HACTOBERFEST2021#5]
Hello Rajat , this is Pushan Verma from BPIT , I have sent pull request to you , Kindly review and accept my PR. Thanks

**Comment by rishabhgupta03** [comment]
there is no pull request from you, kindly open it again and remember not to raise issues notifying about PR's.

**Comment by pushanverma** [comment]
ok , thanks for the instant reply from your side , ill keep that in mind.
